name: cat_me_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shadcn_ui: ^0.12.0
  pro_image_editor: ^6.2.1
  intl: ^0.19.0
  file_picker: 8.1.4
  google_fonts: ^6.2.1
  image: ^4.4.0
  firebase_core: ^3.8.1
  firebase_storage: ^12.3.7
  supabase_flutter: ^2.8.1
  image_picker: ^1.1.2
  mime: ^2.0.0
  url_launcher: ^6.3.1
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
  
dependency_overrides: 
  # Fix conflict with supabase
  mime: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/demo.png
    - assets/frame.png
    - assets/frame1.png
    - assets/google_fonts/